import json
import os
from pathlib import Path
import subprocess
import sys
import time

import numpy as np
import pytest

from spacewalker.geometry import Layout
from spacewalker.hyprland import HyprlandDesktop, create_desktop, hypr
from spacewalker.hyprworker import Outputs, layout_problem


def monitor(name, x=0, y=0, width=1280, height=720, scale=1, transform=0):
    return dict(name=name,x=x,y=y,width=width,height=height,scale=scale,
                transform=transform,refreshRate=60,disabled=False,mirrorOf='none')


def test_layout_validation_detects_overlap_and_keeps_host_geometry():
    original = [monitor('laptop')]
    assert layout_problem(original+[monitor('xr',1280)],original) is None
    assert 'over' in layout_problem(original+[monitor('xr',1279)],original)
    assert 'existing display laptop' in layout_problem([monitor('laptop',2560),monitor('xr')],original)
    assert 'existing display laptop' in layout_problem([monitor('xr')],original)
    # Rotation and fractional scaling change the logical rectangle used for overlap.
    rotated = monitor('portrait', width=1920, height=1080, scale=1.5, transform=1)
    assert layout_problem([rotated,monitor('xr',720)],[rotated]) is None
    assert 'over' in layout_problem([rotated,monitor('xr',719)],[rotated])


@pytest.mark.parametrize('restored_workspace',[False,True])
def test_startup_replaces_stale_rules_before_the_outputs_become_visible(monkeypatch, tmp_path,restored_workspace):
    import re
    monkeypatch.setattr('spacewalker.hyprworker.tempfile.gettempdir', lambda:str(tmp_path))
    (tmp_path/f'spacewalker-native-{os.getuid()}').mkdir()
    original = monitor('laptop')
    current = [original]
    prepared = set()
    workspaces = {}
    activated = []
    expected = {f'Spacewalker-{i+1}' for i in range(3)}
    def ipc(*args, query=False):
        if args[0]=='monitors':
            return list(current)
        if args[0] in ('configerrors','binds'):
            return []
        if args[0]=='keyword':
            raise RuntimeError("keyword can't work with non-legacy parsers. Use eval.")
        if args[0]=='eval':
            match = re.search(r'output="([^"]+)"',args[1])
            if match:
                assert 'position="auto-right"' in args[1]
                assert 'scale=1' in args[1] and 'transform=0' in args[1]
                prepared.add(match[1])
            rule = re.search(r'workspace="name:([^"]+)", monitor="([^"]+)"',args[1])
            if rule:
                workspaces[rule[2]]=rule[1]
            focus = re.search(r'hl.dsp.focus\(\{workspace="name:([^"]+)"',args[1])
            if focus:
                # Reattached output names can restore a numbered workspace even
                # when the requested mode and the new default rule are correct.
                assert 'hl.get_active_window()' in args[1]
                assert 'hl.dsp.focus({window=window})' in args[1]
                assert 'hl.dsp.cursor.move(cursor)' in args[1]
                name = next(n for n,ws in workspaces.items() if ws==focus[1])
                next(m for m in current if m['name']==name)['activeWorkspace']={'name':focus[1]}
                activated.append(name)
        if args[:2]==('output','create'):
            # Simulate the overlap generated by activating a leftover fixed-offset
            # rule before replacing it. All rules must be ready at the first hotplug.
            if prepared != expected or set(workspaces)!=expected:
                raise RuntimeError('Monitor detected overlap with layout')
            output = monitor(args[3],len(current)*1280)
            output['activeWorkspace']={'name':'2' if restored_workspace else workspaces[args[3]]}
            current.append(output)
        if args[:2]==('output','remove'):
            current[:] = [m for m in current if m['name']!=args[2]]
    monkeypatch.setattr('spacewalker.hyprworker.hypr',ipc)
    owner = Outputs(tmp_path,3,1280,720,60,73)
    monkeypatch.setattr(owner,'install_shortcuts',lambda:None)
    try:
        owner.start()
        assert len(owner.monitors)==3
        assert not layout_problem(current,[original])
        assert all(m['activeWorkspace']['name']==workspaces[m['name']] for m in owner.monitors)
        assert set(activated)==(expected if restored_workspace else set())
    finally:
        owner.close()
    assert current==[original]


def test_backend_does_not_silently_substitute_private_desktop(monkeypatch):
    monkeypatch.delenv('HYPRLAND_INSTANCE_SIGNATURE', raising=False)
    with pytest.raises(RuntimeError, match='Native monitors currently require Hyprland'):
        create_desktop(Layout())
    assert not create_desktop(Layout(), backend='private').native


def test_mirror_borrows_output_and_maps_scaled_pointer_without_changing_displays(monkeypatch,tmp_path):
    monkeypatch.setattr('spacewalker.hyprworker.tempfile.gettempdir',lambda:str(tmp_path))
    (tmp_path/f'spacewalker-native-{os.getuid()}').mkdir()
    source = monitor('eDP-1',x=1920,width=1920,height=1080,scale=2)
    source.update(id=0,activeWorkspace={'name':'1'})
    original = [source,monitor('DP-1')]
    calls = []
    def ipc(*args,query=False):
        calls.append(args)
        if args[0]=='monitors': return original
        if args[0]=='binds': return []
    monkeypatch.setattr('spacewalker.hyprworker.hypr',ipc)
    owner = Outputs(tmp_path,1,1920,1080,60,73,source='eDP-1')
    try:
        owner.start()
        assert owner.monitors == [source]
        assert owner.capture_names == ['eDP-1'] and not owner.created
        owner.command({'type':'focus_at','x':960,'y':540})
        assert any('cursor.move({x=2400,y=270})' in a[-1] for a in calls)
    finally:
        owner.close()
    assert not any(a[0] in ('output','keyword') for a in calls)
    assert not any('hl.monitor(' in a[-1] or 'hl.workspace_rule(' in a[-1] for a in calls)


def test_mirror_rejects_multiple_screens_and_private_backend():
    with pytest.raises(RuntimeError,match='single-screen mode'):
        create_desktop(Layout(3),source='eDP-1')
    with pytest.raises(RuntimeError,match='single-screen mode'):
        create_desktop(Layout(1),backend='private',source='eDP-1')


def test_native_input_stays_with_compositor_and_renderer_is_never_moved(monkeypatch, tmp_path):
    calls = []
    def ipc(*args, query=False):
        calls.append(args)
        if args[0]=='activewindow':
            return {'address':'0x123'}
        if args[0]=='clients':
            return [{'address':'0x123','pid':73}]
    monkeypatch.setattr('spacewalker.hyprworker.hypr', ipc)
    owner = Outputs(tmp_path,3,1280,720,60,73)
    for kind in ('motion','key','button','release'):
        owner.command({'type':kind})
    assert not calls
    owner.command({'type':'move_to','screen':0})
    assert not any(args[0]=='dispatch' for args in calls)


def test_native_shortcuts_preserve_existing_bindings(monkeypatch, tmp_path):
    calls = []
    def ipc(*args, query=False):
        calls.append(args)
        if args[0]=='binds':
            return [{'modmask':12,'key':'R','description':'User recenter alternative'}]
    monkeypatch.setattr('spacewalker.hyprworker.hypr', ipc)
    owner = Outputs(tmp_path,3,1280,720,60,73)
    owner.lua = True
    owner.install_shortcuts()
    assert 'R' not in [b['key'] for b in owner.shortcuts]
    assert 'F' in [b['key'] for b in owner.shortcuts]


@pytest.mark.parametrize('lua',[False,True])
def test_launch_targets_the_named_xr_workspace(monkeypatch,lua):
    calls=[]
    monkeypatch.setattr('spacewalker.hyprland.hypr',lambda *args:calls.append(args))
    desktop=HyprlandDesktop(Layout())
    desktop.lua=lua
    desktop.monitors=[{'activeWorkspace':{'name':f'spacewalker_test-{i}'}} for i in range(3)]
    desktop.launch(['example-app','a file'])
    assert len(calls)==1
    assert 'name:spacewalker_test-1 silent' in calls[0][-1]


@pytest.mark.skipif(os.environ.get('SPACEWALKER_NATIVE_TESTS')!='1', reason='Opt-in: attaches temporary real monitors to the host Hyprland session')
@pytest.mark.parametrize('mode',['multiple','single','mirror'])
def test_real_wayland_window_moves_and_survives_monitor_disconnect(mode):
    before = hypr('monitors',query=True)
    before_binds = hypr('binds',query=True)
    before_cursor = hypr('cursorpos',query=True)
    # Exercise the production Full HD mode.
    count = 3 if mode=='multiple' else 1
    layout = Layout(count)
    source = None
    if mode=='mirror':
        candidate = next((m for m in before if m['name'].startswith('eDP') and m.get('transform',0)==0),None)
        if candidate is None:
            pytest.skip('Mirror integration requires a connected unrotated laptop display')
        source = candidate['name']
    desktop = HyprlandDesktop(layout,source=source)
    client = None
    try:
        desktop.start()
        layout = desktop.layout
        assert len(desktop.monitors)==count
        during = hypr('monitors',query=True)
        if source:
            assert {m['name'] for m in during}=={m['name'] for m in before}
        for original in before:
            current = next(m for m in during if m['name']==original['name'])
            for key in ('width','height','scale','x','y'):
                assert current[key]==original[key]
            assert current['activeWorkspace']==original['activeWorkspace']
        if not source:
            assert all(m['activeWorkspace']['name'].startswith('spacewalker_') for m in desktop.monitors)
        env = dict(os.environ, QT_QPA_PLATFORM='wayland')
        client = subprocess.Popen([sys.executable,str(Path(__file__).with_name('wayland_client.py'))],env=env)
        deadline=time.monotonic()+8
        window=None
        while time.monotonic()<deadline:
            window=next((w for w in hypr('clients',query=True) if w['pid']==client.pid),None)
            if window:
                break
            time.sleep(.05)
        assert window and not window['xwayland']
        previous_generations = None
        for screen in ((2,0) if count==3 else (0,)):
            desktop.command(type='move_to',screen=screen,address=window['address'])
            matched=False
            deadline=time.monotonic()+5
            while time.monotonic()<deadline:
                with desktop.frame_view() as frame:
                    if frame is not None:
                        pixels=frame.reshape(layout.height,layout.width*layout.count,4)
                        # Exact test-window red, in BGRA, proves both desktop capture and channel order.
                        mask=np.all(pixels[:,:,:3]==[97,43,231],axis=2)
                        counts=[np.count_nonzero(mask[:,i*layout.width:(i+1)*layout.width]) for i in range(count)]
                        matched=counts[screen]>20000 and sum(counts)-counts[screen]<500
                        del pixels, mask
                frame=None
                if matched:
                    break
                time.sleep(.03)
            if not matched:
                print(json.dumps({'target':screen,'generations':desktop.frame_generations,
                    'window':[w for w in hypr('clients',query=True) if w['pid']==client.pid],
                    'outputs':[{k:m[k] for k in ('name','id','activeWorkspace')} for m in hypr('monitors',query=True)]}))
            assert matched, (counts,desktop.log_text())
            generations = desktop.frame_generations[:count]
            assert len(generations)==count and all(g>0 for g in generations)
            if previous_generations:
                assert generations[screen]>previous_generations[screen]
            previous_generations = generations
            real=next(w for w in hypr('clients',query=True) if w['pid']==client.pid)
            assert real['monitor']==desktop.monitors[screen]['id']
        # Cursor-only changes on an otherwise static desktop must still arrive.
        # Capture includes the compositor cursor; no synthetic viewer cursor is used.
        def wait_cursor(x,y):
            desktop.command(type='focus_at',x=x,y=y)
            deadline=time.monotonic()+3
            while time.monotonic()<deadline:
                data=desktop.frame()
                if data is not None:
                    pixels=np.frombuffer(data,dtype=np.uint8).reshape(layout.height,layout.width*layout.count,4)
                    patch=pixels[y:y+48,x:x+48,:3]
                    if np.count_nonzero(np.any(patch!=[97,43,231],axis=2))>20:
                        return patch.copy()
                time.sleep(.01)
            raise AssertionError('Compositor cursor did not reach the captured monitor')
        if not source:
            wait_cursor(220,160)
            wait_cursor(300,200)
        # Simulate GUI death: guardian observes EOF and removes monitors on its own.
        desktop.worker.stdin.close()
        desktop.worker.wait(timeout=8)
        assert client.poll() is None
        remaining=hypr('monitors',query=True)
        for original in before:
            current=next(m for m in remaining if m['name']==original['name'])
            for key in ('width','height','scale','x','y'):
                assert current[key]==original[key]
        assert {m['name'] for m in remaining}=={m['name'] for m in before}
        assert hypr('binds',query=True)==before_binds
        assert not any(e.strip() for e in hypr('configerrors',query=True))
    finally:
        try:
            if getattr(desktop,'lua',False):
                hypr('eval',f'hl.dispatch(hl.dsp.cursor.move({{x={before_cursor["x"]},y={before_cursor["y"]}}}))')
            else:
                hypr('dispatch','movecursor',f'{before_cursor["x"]} {before_cursor["y"]}')
        finally:
            desktop.close()
        if client:
            client.terminate()
            client.wait(timeout=3)
